name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: phyton instalation
        run: sudo apt install python3.8
      - name: flask dependecies instalation
        run: pip install flask
      - name: firebase dependecies instalation
        run: pip install firebase
      - name: flake8 install
        run: sudo apt-get install -y flake8
      - name:  pip flake8 install
        run: pip install flake8
      - name: revision
        run: flake8 .\app.py
      - name: zip addition
        uses: actions/upload-artifact@v2
        with:
          path: app.py
